//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ÖğrenciNotMvc.Models.EntityFrameWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_kulüpler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_kulüpler()
        {
            this.tbl_öğrenciler = new HashSet<tbl_öğrenciler>();
        }
    
        public byte KulüpID { get; set; }
        public string KulüpAd { get; set; }
        public Nullable<short> KulüpKontenjan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_öğrenciler> tbl_öğrenciler { get; set; }
    }
}
