//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ÖğrenciNotMvc.Models.EntityFrameWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_öğrenciler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_öğrenciler()
        {
            this.tbl_notlar = new HashSet<tbl_notlar>();
        }
    
        public int ÖğrenciID { get; set; }
        public string ÖğrAD { get; set; }
        public string ÖğrSoyad { get; set; }
        public string ÖğrFotoğraf { get; set; }
        public string ÖğrCinsiyet { get; set; }
        public Nullable<byte> ÖğrKulüp { get; set; }
    
        public virtual tbl_kulüpler tbl_kulüpler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_notlar> tbl_notlar { get; set; }
    }
}
